// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_grants.sql

package sqlc

import (
	"context"
)

const agentGrantCount = `-- name: AgentGrantCount :one
SELECT count(*) FROM agent_grants WHERE tenant_id=?
`

func (q *Queries) AgentGrantCount(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, agentGrantCount, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentGrant = `-- name: CreateAgentGrant :exec
INSERT INTO agent_grants(id,tenant_id,digest,scopes,created_at,expires_at,label) VALUES(?,?,?,?,?,?,?)
`

type CreateAgentGrantParams struct {
	ID        string
	TenantID  string
	Digest    []byte
	Scopes    int64
	CreatedAt int64
	ExpiresAt int64
	Label     string
}

func (q *Queries) CreateAgentGrant(ctx context.Context, arg CreateAgentGrantParams) error {
	_, err := q.db.ExecContext(ctx, createAgentGrant,
		arg.ID,
		arg.TenantID,
		arg.Digest,
		arg.Scopes,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Label,
	)
	return err
}

const deleteAgentGrants = `-- name: DeleteAgentGrants :exec
DELETE FROM agent_grants WHERE tenant_id=?
`

func (q *Queries) DeleteAgentGrants(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentGrants, tenantID)
	return err
}

const lookupAgentGrant = `-- name: LookupAgentGrant :one
SELECT id, tenant_id, digest, scopes, created_at, expires_at, revoked_at, last_used_at, label FROM agent_grants WHERE id=?
`

func (q *Queries) LookupAgentGrant(ctx context.Context, id string) (AgentGrant, error) {
	row := q.db.QueryRowContext(ctx, lookupAgentGrant, id)
	var i AgentGrant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Digest,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.Label,
	)
	return i, err
}

const revokeAgentGrant = `-- name: RevokeAgentGrant :execrows
UPDATE agent_grants SET revoked_at=coalesce(revoked_at,max(created_at,?)) WHERE tenant_id=? AND id=?
`

type RevokeAgentGrantParams struct {
	MAX      interface{}
	TenantID string
	ID       string
}

func (q *Queries) RevokeAgentGrant(ctx context.Context, arg RevokeAgentGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAgentGrant, arg.MAX, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAgentGrant = `-- name: TouchAgentGrant :execrows
UPDATE agent_grants SET last_used_at=max(coalesce(last_used_at,created_at),?) WHERE tenant_id=? AND id=? AND revoked_at IS NULL AND created_at<=? AND expires_at>?
`

type TouchAgentGrantParams struct {
	MAX       interface{}
	TenantID  string
	ID        string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) TouchAgentGrant(ctx context.Context, arg TouchAgentGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchAgentGrant,
		arg.MAX,
		arg.TenantID,
		arg.ID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
