// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collection.sql

package sqlc

import (
	"context"
)

const appendCollectionEvent = `-- name: AppendCollectionEvent :exec
INSERT INTO collection_events(tenant_id,source_id,item_id,revision,payload) VALUES(?1,?2,?3,?4,?5)
`

type AppendCollectionEventParams struct {
	TenantID string
	SourceID string
	ItemID   string
	Revision int64
	Payload  string
}

func (q *Queries) AppendCollectionEvent(ctx context.Context, arg AppendCollectionEventParams) error {
	_, err := q.db.ExecContext(ctx, appendCollectionEvent,
		arg.TenantID,
		arg.SourceID,
		arg.ItemID,
		arg.Revision,
		arg.Payload,
	)
	return err
}

const collectionEvents = `-- name: CollectionEvents :many
SELECT sequence,payload FROM collection_events WHERE tenant_id=?1 AND sequence>?2 ORDER BY sequence LIMIT 100
`

type CollectionEventsParams struct {
	TenantID    string
	AfterCursor int64
}

type CollectionEventsRow struct {
	Sequence int64
	Payload  string
}

func (q *Queries) CollectionEvents(ctx context.Context, arg CollectionEventsParams) ([]CollectionEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, collectionEvents, arg.TenantID, arg.AfterCursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionEventsRow{}
	for rows.Next() {
		var i CollectionEventsRow
		if err := rows.Scan(&i.Sequence, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectionHostDue = `-- name: CollectionHostDue :one
SELECT CAST(coalesce((SELECT next_at FROM collection_hosts WHERE host=?1),0) AS INTEGER)
`

func (q *Queries) CollectionHostDue(ctx context.Context, host string) (int64, error) {
	row := q.db.QueryRowContext(ctx, collectionHostDue, host)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const collectionItem = `-- name: CollectionItem :one
SELECT revision,fingerprint,payload FROM collection_items WHERE tenant_id=?1 AND id=?2
`

type CollectionItemParams struct {
	TenantID string
	ID       string
}

type CollectionItemRow struct {
	Revision    int64
	Fingerprint string
	Payload     string
}

func (q *Queries) CollectionItem(ctx context.Context, arg CollectionItemParams) (CollectionItemRow, error) {
	row := q.db.QueryRowContext(ctx, collectionItem, arg.TenantID, arg.ID)
	var i CollectionItemRow
	err := row.Scan(&i.Revision, &i.Fingerprint, &i.Payload)
	return i, err
}

const collectionSeedMode = `-- name: CollectionSeedMode :one
SELECT mode FROM poll_sources WHERE tenant_id=?1 AND source_id=?2
`

type CollectionSeedModeParams struct {
	TenantID string
	SourceID string
}

func (q *Queries) CollectionSeedMode(ctx context.Context, arg CollectionSeedModeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, collectionSeedMode, arg.TenantID, arg.SourceID)
	var mode string
	err := row.Scan(&mode)
	return mode, err
}

const collectionSourceCount = `-- name: CollectionSourceCount :one
SELECT count(*) FROM collection_items WHERE tenant_id=?1 AND source_id=?2
`

type CollectionSourceCountParams struct {
	TenantID string
	SourceID string
}

func (q *Queries) CollectionSourceCount(ctx context.Context, arg CollectionSourceCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, collectionSourceCount, arg.TenantID, arg.SourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const collectionSourceItems = `-- name: CollectionSourceItems :many
SELECT payload FROM collection_items WHERE tenant_id=?1 AND source_id=?2 ORDER BY id LIMIT 5001
`

type CollectionSourceItemsParams struct {
	TenantID string
	SourceID string
}

func (q *Queries) CollectionSourceItems(ctx context.Context, arg CollectionSourceItemsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, collectionSourceItems, arg.TenantID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var payload string
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectionStatus = `-- name: CollectionStatus :one
SELECT CAST((SELECT count(*) FROM poll_sources ps WHERE ps.tenant_id=?1 AND ps.mode='html') AS INTEGER) AS seeds,
CAST((SELECT count(*) FROM poll_sources ps WHERE ps.tenant_id=?1 AND ps.mode='html' AND approved=1 AND enabled=1) AS INTEGER) AS enabled,
CAST((SELECT count(*) FROM collection_items ci WHERE ci.tenant_id=?1) AS INTEGER) AS items,
CAST((SELECT count(*) FROM collection_events ce WHERE ce.tenant_id=?1) AS INTEGER) AS revisions
`

type CollectionStatusRow struct {
	Seeds     int64
	Enabled   int64
	Items     int64
	Revisions int64
}

func (q *Queries) CollectionStatus(ctx context.Context, tenantID string) (CollectionStatusRow, error) {
	row := q.db.QueryRowContext(ctx, collectionStatus, tenantID)
	var i CollectionStatusRow
	err := row.Scan(
		&i.Seeds,
		&i.Enabled,
		&i.Items,
		&i.Revisions,
	)
	return i, err
}

const collectionVersionCount = `-- name: CollectionVersionCount :one
SELECT count(*) FROM collection_events WHERE tenant_id=?1 AND source_id=?2
`

type CollectionVersionCountParams struct {
	TenantID string
	SourceID string
}

func (q *Queries) CollectionVersionCount(ctx context.Context, arg CollectionVersionCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, collectionVersionCount, arg.TenantID, arg.SourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCollectionEvents = `-- name: DeleteCollectionEvents :exec
DELETE FROM collection_events WHERE tenant_id=?
`

func (q *Queries) DeleteCollectionEvents(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCollectionEvents, tenantID)
	return err
}

const deleteCollectionItems = `-- name: DeleteCollectionItems :exec
DELETE FROM collection_items WHERE tenant_id=?
`

func (q *Queries) DeleteCollectionItems(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCollectionItems, tenantID)
	return err
}

const holdCollectionHost = `-- name: HoldCollectionHost :exec
INSERT INTO collection_hosts(host,next_at) VALUES(?1,?2) ON CONFLICT(host) DO UPDATE SET next_at=max(next_at,excluded.next_at)
`

type HoldCollectionHostParams struct {
	Host   string
	NextAt int64
}

func (q *Queries) HoldCollectionHost(ctx context.Context, arg HoldCollectionHostParams) error {
	_, err := q.db.ExecContext(ctx, holdCollectionHost, arg.Host, arg.NextAt)
	return err
}

const putCollectionItem = `-- name: PutCollectionItem :exec
INSERT INTO collection_items(tenant_id,source_id,id,revision,fingerprint,payload) VALUES(?1,?2,?3,?4,?5,?6) ON CONFLICT(tenant_id,id) DO UPDATE SET revision=excluded.revision,fingerprint=excluded.fingerprint,payload=excluded.payload
`

type PutCollectionItemParams struct {
	TenantID    string
	SourceID    string
	ID          string
	Revision    int64
	Fingerprint string
	Payload     string
}

func (q *Queries) PutCollectionItem(ctx context.Context, arg PutCollectionItemParams) error {
	_, err := q.db.ExecContext(ctx, putCollectionItem,
		arg.TenantID,
		arg.SourceID,
		arg.ID,
		arg.Revision,
		arg.Fingerprint,
		arg.Payload,
	)
	return err
}

const setCollectionMode = `-- name: SetCollectionMode :exec
UPDATE poll_sources SET mode='html',preview_allowed=?1,robots_until=?2 WHERE tenant_id=?3 AND source_id=?4
`

type SetCollectionModeParams struct {
	PreviewAllowed int64
	RobotsUntil    int64
	TenantID       string
	SourceID       string
}

func (q *Queries) SetCollectionMode(ctx context.Context, arg SetCollectionModeParams) error {
	_, err := q.db.ExecContext(ctx, setCollectionMode,
		arg.PreviewAllowed,
		arg.RobotsUntil,
		arg.TenantID,
		arg.SourceID,
	)
	return err
}
