// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: corpus.sql

package sqlc

import (
	"context"
	"database/sql"
)

const attachSource = `-- name: AttachSource :exec
INSERT INTO feed_sources(tenant_id,feed_id,source_id) VALUES(?,?,?)
`

type AttachSourceParams struct {
	TenantID string
	FeedID   string
	SourceID string
}

func (q *Queries) AttachSource(ctx context.Context, arg AttachSourceParams) error {
	_, err := q.db.ExecContext(ctx, attachSource, arg.TenantID, arg.FeedID, arg.SourceID)
	return err
}

const createFeed = `-- name: CreateFeed :exec
INSERT INTO feeds(tenant_id,id,title) VALUES(?,?,?)
`

type CreateFeedParams struct {
	TenantID string
	ID       string
	Title    string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) error {
	_, err := q.db.ExecContext(ctx, createFeed, arg.TenantID, arg.ID, arg.Title)
	return err
}

const createSource = `-- name: CreateSource :exec
INSERT INTO sources(tenant_id,id,url,title) VALUES(?,?,?,?)
`

type CreateSourceParams struct {
	TenantID string
	ID       string
	Url      string
	Title    string
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) error {
	_, err := q.db.ExecContext(ctx, createSource,
		arg.TenantID,
		arg.ID,
		arg.Url,
		arg.Title,
	)
	return err
}

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants(id,created_at) VALUES(?,?)
`

type CreateTenantParams struct {
	ID        string
	CreatedAt int64
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.ExecContext(ctx, createTenant, arg.ID, arg.CreatedAt)
	return err
}

const deleteArticle = `-- name: DeleteArticle :execrows
DELETE FROM articles WHERE tenant_id=? AND id=?
`

type DeleteArticleParams struct {
	TenantID string
	ID       string
}

func (q *Queries) DeleteArticle(ctx context.Context, arg DeleteArticleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteArticle, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getArticle = `-- name: GetArticle :one
SELECT a.id,a.source_id,a.origin_id,a.url,a.title,a.body,a.content_hash,a.published_at,a.observed_at FROM articles a JOIN sources s ON s.tenant_id=a.tenant_id AND s.id=a.source_id WHERE a.tenant_id=? AND a.id=? AND s.enabled=1
`

type GetArticleParams struct {
	TenantID string
	ID       string
}

type GetArticleRow struct {
	ID          string
	SourceID    string
	OriginID    string
	Url         string
	Title       string
	Body        string
	ContentHash string
	PublishedAt sql.NullInt64
	ObservedAt  int64
}

func (q *Queries) GetArticle(ctx context.Context, arg GetArticleParams) (GetArticleRow, error) {
	row := q.db.QueryRowContext(ctx, getArticle, arg.TenantID, arg.ID)
	var i GetArticleRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.OriginID,
		&i.Url,
		&i.Title,
		&i.Body,
		&i.ContentHash,
		&i.PublishedAt,
		&i.ObservedAt,
	)
	return i, err
}

const putArticle = `-- name: PutArticle :execrows
INSERT INTO articles(tenant_id,id,source_id,origin_id,url,title,body,content_hash,published_at,observed_at)
VALUES(?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(tenant_id,id) DO UPDATE SET
url=excluded.url,title=excluded.title,body=excluded.body,content_hash=excluded.content_hash,
published_at=excluded.published_at,observed_at=excluded.observed_at
WHERE articles.source_id=excluded.source_id AND articles.origin_id=excluded.origin_id
`

type PutArticleParams struct {
	TenantID    string
	ID          string
	SourceID    string
	OriginID    string
	Url         string
	Title       string
	Body        string
	ContentHash string
	PublishedAt sql.NullInt64
	ObservedAt  int64
}

func (q *Queries) PutArticle(ctx context.Context, arg PutArticleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, putArticle,
		arg.TenantID,
		arg.ID,
		arg.SourceID,
		arg.OriginID,
		arg.Url,
		arg.Title,
		arg.Body,
		arg.ContentHash,
		arg.PublishedAt,
		arg.ObservedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordVersion = `-- name: RecordVersion :exec
INSERT INTO article_versions(tenant_id,article_id,content_hash,title,body,observed_at)
VALUES(?,?,?,?,?,?) ON CONFLICT(tenant_id,article_id,content_hash) DO NOTHING
`

type RecordVersionParams struct {
	TenantID    string
	ArticleID   string
	ContentHash string
	Title       string
	Body        string
	ObservedAt  int64
}

func (q *Queries) RecordVersion(ctx context.Context, arg RecordVersionParams) error {
	_, err := q.db.ExecContext(ctx, recordVersion,
		arg.TenantID,
		arg.ArticleID,
		arg.ContentHash,
		arg.Title,
		arg.Body,
		arg.ObservedAt,
	)
	return err
}
