// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cleanAssertionReplays = `-- name: CleanAssertionReplays :exec
DELETE FROM assertion_replays WHERE expires_at < ?
`

func (q *Queries) CleanAssertionReplays(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, cleanAssertionReplays, expiresAt)
	return err
}

const cleanRequestBudgets = `-- name: CleanRequestBudgets :exec
DELETE FROM request_budgets WHERE window < ?
`

func (q *Queries) CleanRequestBudgets(ctx context.Context, window int64) error {
	_, err := q.db.ExecContext(ctx, cleanRequestBudgets, window)
	return err
}

const consumeAssertion = `-- name: ConsumeAssertion :execrows
INSERT INTO assertion_replays(issuer,id,expires_at) VALUES(?,?,?) ON CONFLICT DO NOTHING
`

type ConsumeAssertionParams struct {
	Issuer    string
	ID        string
	ExpiresAt int64
}

func (q *Queries) ConsumeAssertion(ctx context.Context, arg ConsumeAssertionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeAssertion, arg.Issuer, arg.ID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeRequestBudget = `-- name: ConsumeRequestBudget :execrows
INSERT INTO request_budgets(tenant_id,window,used) VALUES(?,?,1)
ON CONFLICT(tenant_id,window) DO UPDATE SET used=used+1 WHERE used<60
`

type ConsumeRequestBudgetParams struct {
	TenantID string
	Window   int64
}

func (q *Queries) ConsumeRequestBudget(ctx context.Context, arg ConsumeRequestBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeRequestBudget, arg.TenantID, arg.Window)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAssertionReplays = `-- name: CountAssertionReplays :one
SELECT count(*) FROM assertion_replays
`

func (q *Queries) CountAssertionReplays(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssertionReplays)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomerKeys = `-- name: CountCustomerKeys :one
SELECT count(*) FROM api_keys k JOIN customer_key_expiry e ON e.key_id=k.id
WHERE k.tenant_id=? AND k.revoked_at IS NULL AND e.expires_at>?
`

type CountCustomerKeysParams struct {
	TenantID  string
	ExpiresAt int64
}

func (q *Queries) CountCustomerKeys(ctx context.Context, arg CountCustomerKeysParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomerKeys, arg.TenantID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomerKeyExpiry = `-- name: CreateCustomerKeyExpiry :exec
INSERT INTO customer_key_expiry(key_id,expires_at) VALUES(?,?)
`

type CreateCustomerKeyExpiryParams struct {
	KeyID     string
	ExpiresAt int64
}

func (q *Queries) CreateCustomerKeyExpiry(ctx context.Context, arg CreateCustomerKeyExpiryParams) error {
	_, err := q.db.ExecContext(ctx, createCustomerKeyExpiry, arg.KeyID, arg.ExpiresAt)
	return err
}

const customerKeyExpiry = `-- name: CustomerKeyExpiry :one
SELECT expires_at FROM customer_key_expiry WHERE key_id=?
`

func (q *Queries) CustomerKeyExpiry(ctx context.Context, keyID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, customerKeyExpiry, keyID)
	var expires_at int64
	err := row.Scan(&expires_at)
	return expires_at, err
}

const ensureCustomerWorkspace = `-- name: EnsureCustomerWorkspace :exec
INSERT INTO customer_workspaces(tenant_id,created_at) VALUES(?,?) ON CONFLICT DO NOTHING
`

type EnsureCustomerWorkspaceParams struct {
	TenantID  string
	CreatedAt int64
}

func (q *Queries) EnsureCustomerWorkspace(ctx context.Context, arg EnsureCustomerWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, ensureCustomerWorkspace, arg.TenantID, arg.CreatedAt)
	return err
}

const listCustomerFeeds = `-- name: ListCustomerFeeds :many
SELECT id,title FROM feeds WHERE tenant_id=? AND enabled=1 ORDER BY id LIMIT 100
`

type ListCustomerFeedsRow struct {
	ID    string
	Title string
}

func (q *Queries) ListCustomerFeeds(ctx context.Context, tenantID string) ([]ListCustomerFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomerFeeds, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerFeedsRow{}
	for rows.Next() {
		var i ListCustomerFeedsRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerKeys = `-- name: ListCustomerKeys :many
SELECT k.id,k.scopes,k.created_at,k.last_used_at,k.revoked_at,e.expires_at
FROM api_keys k JOIN customer_key_expiry e ON e.key_id=k.id
WHERE k.tenant_id=? ORDER BY k.created_at DESC,k.id LIMIT 100
`

type ListCustomerKeysRow struct {
	ID         string
	Scopes     int64
	CreatedAt  int64
	LastUsedAt sql.NullInt64
	RevokedAt  sql.NullInt64
	ExpiresAt  int64
}

func (q *Queries) ListCustomerKeys(ctx context.Context, tenantID string) ([]ListCustomerKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomerKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerKeysRow{}
	for rows.Next() {
		var i ListCustomerKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requireCustomerWorkspace = `-- name: RequireCustomerWorkspace :one
SELECT tenant_id FROM customer_workspaces WHERE tenant_id=?
`

func (q *Queries) RequireCustomerWorkspace(ctx context.Context, tenantID string) (string, error) {
	row := q.db.QueryRowContext(ctx, requireCustomerWorkspace, tenantID)
	var tenant_id string
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
