// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_lifecycle.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteCustomerArticles = `-- name: DeleteCustomerArticles :exec
DELETE FROM articles WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerArticles(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerArticles, tenantID)
	return err
}

const deleteCustomerBudgets = `-- name: DeleteCustomerBudgets :exec
DELETE FROM budgets WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerBudgets(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerBudgets, tenantID)
	return err
}

const deleteCustomerFeedSources = `-- name: DeleteCustomerFeedSources :exec
DELETE FROM feed_sources WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerFeedSources(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerFeedSources, tenantID)
	return err
}

const deleteCustomerFeedback = `-- name: DeleteCustomerFeedback :exec
DELETE FROM feedback_events WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerFeedback(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerFeedback, tenantID)
	return err
}

const deleteCustomerFeeds = `-- name: DeleteCustomerFeeds :exec
DELETE FROM feeds WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerFeeds(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerFeeds, tenantID)
	return err
}

const deleteCustomerKeyExpiries = `-- name: DeleteCustomerKeyExpiries :exec
DELETE FROM customer_key_expiry WHERE key_id IN (SELECT id FROM api_keys WHERE tenant_id=?)
`

func (q *Queries) DeleteCustomerKeyExpiries(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerKeyExpiries, tenantID)
	return err
}

const deleteCustomerKeys = `-- name: DeleteCustomerKeys :exec
DELETE FROM api_keys WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerKeys(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerKeys, tenantID)
	return err
}

const deleteCustomerMarker = `-- name: DeleteCustomerMarker :exec
UPDATE customer_workspaces SET state='deleted' WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerMarker(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerMarker, tenantID)
	return err
}

const deleteCustomerPollAttempts = `-- name: DeleteCustomerPollAttempts :exec
DELETE FROM poll_attempts WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerPollAttempts(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerPollAttempts, tenantID)
	return err
}

const deleteCustomerPollCursors = `-- name: DeleteCustomerPollCursors :exec
DELETE FROM poll_cursors WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerPollCursors(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerPollCursors, tenantID)
	return err
}

const deleteCustomerPollSources = `-- name: DeleteCustomerPollSources :exec
DELETE FROM poll_sources WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerPollSources(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerPollSources, tenantID)
	return err
}

const deleteCustomerRequests = `-- name: DeleteCustomerRequests :exec
DELETE FROM request_budgets WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerRequests(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerRequests, tenantID)
	return err
}

const deleteCustomerSnapshots = `-- name: DeleteCustomerSnapshots :exec
DELETE FROM query_snapshots WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerSnapshots(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerSnapshots, tenantID)
	return err
}

const deleteCustomerSources = `-- name: DeleteCustomerSources :exec
DELETE FROM sources WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerSources(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerSources, tenantID)
	return err
}

const deleteCustomerWork = `-- name: DeleteCustomerWork :exec
DELETE FROM query_work WHERE tenant_id=?
`

func (q *Queries) DeleteCustomerWork(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerWork, tenantID)
	return err
}

const expireErasedAcquisitionUsage = `-- name: ExpireErasedAcquisitionUsage :exec
DELETE FROM erased_acquisition_usage WHERE charged_at<=?
`

func (q *Queries) ExpireErasedAcquisitionUsage(ctx context.Context, chargedAt int64) error {
	_, err := q.db.ExecContext(ctx, expireErasedAcquisitionUsage, chargedAt)
	return err
}

const exportCustomerArticles = `-- name: ExportCustomerArticles :many
SELECT id,source_id,url,title,published_at,observed_at FROM articles WHERE tenant_id=? ORDER BY id LIMIT 100 OFFSET ?
`

type ExportCustomerArticlesParams struct {
	TenantID string
	Offset   int64
}

type ExportCustomerArticlesRow struct {
	ID          string
	SourceID    string
	Url         string
	Title       string
	PublishedAt sql.NullInt64
	ObservedAt  int64
}

func (q *Queries) ExportCustomerArticles(ctx context.Context, arg ExportCustomerArticlesParams) ([]ExportCustomerArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, exportCustomerArticles, arg.TenantID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportCustomerArticlesRow{}
	for rows.Next() {
		var i ExportCustomerArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Url,
			&i.Title,
			&i.PublishedAt,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCustomerFeedback = `-- name: ExportCustomerFeedback :many
SELECT id,snapshot_id,article_id,feed_id,action,reverses_event_id,created_at FROM feedback_events WHERE tenant_id=? ORDER BY id LIMIT 100 OFFSET ?
`

type ExportCustomerFeedbackParams struct {
	TenantID string
	Offset   int64
}

type ExportCustomerFeedbackRow struct {
	ID              string
	SnapshotID      string
	ArticleID       string
	FeedID          string
	Action          string
	ReversesEventID sql.NullString
	CreatedAt       int64
}

func (q *Queries) ExportCustomerFeedback(ctx context.Context, arg ExportCustomerFeedbackParams) ([]ExportCustomerFeedbackRow, error) {
	rows, err := q.db.QueryContext(ctx, exportCustomerFeedback, arg.TenantID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportCustomerFeedbackRow{}
	for rows.Next() {
		var i ExportCustomerFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.ArticleID,
			&i.FeedID,
			&i.Action,
			&i.ReversesEventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCustomerFeeds = `-- name: ExportCustomerFeeds :many
SELECT id,title,enabled FROM feeds WHERE tenant_id=? ORDER BY id LIMIT 100 OFFSET ?
`

type ExportCustomerFeedsParams struct {
	TenantID string
	Offset   int64
}

type ExportCustomerFeedsRow struct {
	ID      string
	Title   string
	Enabled int64
}

func (q *Queries) ExportCustomerFeeds(ctx context.Context, arg ExportCustomerFeedsParams) ([]ExportCustomerFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportCustomerFeeds, arg.TenantID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportCustomerFeedsRow{}
	for rows.Next() {
		var i ExportCustomerFeedsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCustomerSnapshots = `-- name: ExportCustomerSnapshots :many
SELECT id,feed_id,mode,generated_at,expires_at,items FROM query_snapshots WHERE tenant_id=? ORDER BY id LIMIT 10 OFFSET ?
`

type ExportCustomerSnapshotsParams struct {
	TenantID string
	Offset   int64
}

type ExportCustomerSnapshotsRow struct {
	ID          string
	FeedID      string
	Mode        string
	GeneratedAt int64
	ExpiresAt   int64
	Items       string
}

func (q *Queries) ExportCustomerSnapshots(ctx context.Context, arg ExportCustomerSnapshotsParams) ([]ExportCustomerSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportCustomerSnapshots, arg.TenantID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportCustomerSnapshotsRow{}
	for rows.Next() {
		var i ExportCustomerSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Mode,
			&i.GeneratedAt,
			&i.ExpiresAt,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCustomerSources = `-- name: ExportCustomerSources :many
SELECT id,url,title,enabled FROM sources WHERE tenant_id=? ORDER BY id LIMIT 100 OFFSET ?
`

type ExportCustomerSourcesParams struct {
	TenantID string
	Offset   int64
}

type ExportCustomerSourcesRow struct {
	ID      string
	Url     string
	Title   string
	Enabled int64
}

func (q *Queries) ExportCustomerSources(ctx context.Context, arg ExportCustomerSourcesParams) ([]ExportCustomerSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, exportCustomerSources, arg.TenantID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportCustomerSourcesRow{}
	for rows.Next() {
		var i ExportCustomerSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const preserveErasedAcquisitionUsage = `-- name: PreserveErasedAcquisitionUsage :exec
INSERT INTO erased_acquisition_usage(charged_at,charged_bytes)
SELECT max(charged_at,lease_until),charged_bytes FROM poll_attempts WHERE tenant_id=?
`

func (q *Queries) PreserveErasedAcquisitionUsage(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, preserveErasedAcquisitionUsage, tenantID)
	return err
}

const suspendCustomer = `-- name: SuspendCustomer :execrows
UPDATE customer_workspaces SET state='suspended' WHERE tenant_id=? AND state='active'
`

func (q *Queries) SuspendCustomer(ctx context.Context, tenantID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, suspendCustomer, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
