// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package sqlc

import (
	"context"
	"database/sql"
)

const advanceFeedbackRevision = `-- name: AdvanceFeedbackRevision :execrows
UPDATE feeds SET revision=revision+1 WHERE tenant_id=? AND id=? AND enabled=1
`

type AdvanceFeedbackRevisionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) AdvanceFeedbackRevision(ctx context.Context, arg AdvanceFeedbackRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceFeedbackRevision, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createFeedbackEvent = `-- name: CreateFeedbackEvent :execrows
INSERT INTO feedback_events(tenant_id,id,snapshot_id,article_id,feed_id,action,reverses_event_id,created_at) VALUES(?,?,?,?,?,?,?,?)
`

type CreateFeedbackEventParams struct {
	TenantID        string
	ID              string
	SnapshotID      string
	ArticleID       string
	FeedID          string
	Action          string
	ReversesEventID sql.NullString
	CreatedAt       int64
}

func (q *Queries) CreateFeedbackEvent(ctx context.Context, arg CreateFeedbackEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createFeedbackEvent,
		arg.TenantID,
		arg.ID,
		arg.SnapshotID,
		arg.ArticleID,
		arg.FeedID,
		arg.Action,
		arg.ReversesEventID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const feedbackEvent = `-- name: FeedbackEvent :one
SELECT tenant_id, id, snapshot_id, article_id, feed_id, "action", reverses_event_id, created_at FROM feedback_events WHERE tenant_id=? AND id=?
`

type FeedbackEventParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FeedbackEvent(ctx context.Context, arg FeedbackEventParams) (FeedbackEvent, error) {
	row := q.db.QueryRowContext(ctx, feedbackEvent, arg.TenantID, arg.ID)
	var i FeedbackEvent
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.SnapshotID,
		&i.ArticleID,
		&i.FeedID,
		&i.Action,
		&i.ReversesEventID,
		&i.CreatedAt,
	)
	return i, err
}

const feedbackReversal = `-- name: FeedbackReversal :one
SELECT id FROM feedback_events WHERE tenant_id=? AND reverses_event_id=?
`

type FeedbackReversalParams struct {
	TenantID        string
	ReversesEventID sql.NullString
}

func (q *Queries) FeedbackReversal(ctx context.Context, arg FeedbackReversalParams) (string, error) {
	row := q.db.QueryRowContext(ctx, feedbackReversal, arg.TenantID, arg.ReversesEventID)
	var id string
	err := row.Scan(&id)
	return id, err
}
