// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys(id,tenant_id,digest,scopes,created_at) VALUES(?,?,?,?,?)
`

type CreateAPIKeyParams struct {
	ID        string
	TenantID  string
	Digest    []byte
	Scopes    int64
	CreatedAt int64
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.TenantID,
		arg.Digest,
		arg.Scopes,
		arg.CreatedAt,
	)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT id,title FROM feeds WHERE tenant_id=? AND id=? AND enabled=1
`

type GetFeedParams struct {
	TenantID string
	ID       string
}

type GetFeedRow struct {
	ID    string
	Title string
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) (GetFeedRow, error) {
	row := q.db.QueryRowContext(ctx, getFeed, arg.TenantID, arg.ID)
	var i GetFeedRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const lookupAPIKey = `-- name: LookupAPIKey :one
SELECT id,tenant_id,digest,scopes,created_at,last_used_at,revoked_at FROM api_keys WHERE id=?
`

func (q *Queries) LookupAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, lookupAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Digest,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at=coalesce(revoked_at,max(created_at,?)) WHERE tenant_id=? AND id=?
`

type RevokeAPIKeyParams struct {
	MAX      interface{}
	TenantID string
	ID       string
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIKey, arg.MAX, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAPIKey = `-- name: TouchAPIKey :execrows
UPDATE api_keys SET last_used_at=max(coalesce(last_used_at,created_at),?)
WHERE tenant_id=? AND id=? AND revoked_at IS NULL
`

type TouchAPIKeyParams struct {
	MAX      interface{}
	TenantID string
	ID       string
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchAPIKey, arg.MAX, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
