// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package sqlc

import (
	"context"
	"database/sql"
)

const abandonPollAttempts = `-- name: AbandonPollAttempts :exec
UPDATE poll_attempts SET state='abandoned',charged_at=lease_until WHERE state='pending' AND lease_until<=?1
`

func (q *Queries) AbandonPollAttempts(ctx context.Context, nowAt int64) error {
	_, err := q.db.ExecContext(ctx, abandonPollAttempts, nowAt)
	return err
}

const abandonPollSources = `-- name: AbandonPollSources :exec
UPDATE poll_sources SET claim_id=NULL,last_error='abandoned'
WHERE claim_id IN (SELECT id FROM poll_attempts WHERE state='pending' AND lease_until<=?1)
`

func (q *Queries) AbandonPollSources(ctx context.Context, nowAt int64) error {
	_, err := q.db.ExecContext(ctx, abandonPollSources, nowAt)
	return err
}

const activePollAttempts = `-- name: ActivePollAttempts :one
SELECT count(*) FROM poll_attempts WHERE state='pending'
`

func (q *Queries) ActivePollAttempts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, activePollAttempts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const advancePollCursor = `-- name: AdvancePollCursor :exec
INSERT INTO poll_cursors(tenant_id,source_id) VALUES(?1,?2) ON CONFLICT(tenant_id) DO UPDATE SET source_id=excluded.source_id
`

type AdvancePollCursorParams struct {
	TenantID string
	SourceID string
}

func (q *Queries) AdvancePollCursor(ctx context.Context, arg AdvancePollCursorParams) error {
	_, err := q.db.ExecContext(ctx, advancePollCursor, arg.TenantID, arg.SourceID)
	return err
}

const configurePoll = `-- name: ConfigurePoll :exec
INSERT INTO poll_sources(tenant_id,source_id,approved_url,approved,enabled,interval_us,max_bytes,next_at)
VALUES(?1,?2,?3,?4,?5,?6,?7,?8) ON CONFLICT(tenant_id,source_id) DO UPDATE SET
approved_url=excluded.approved_url,approved=excluded.approved,enabled=excluded.enabled,
interval_us=excluded.interval_us,max_bytes=excluded.max_bytes,
next_at=max(poll_sources.next_at,excluded.next_at),etag='',modified='',claim_id=NULL
`

type ConfigurePollParams struct {
	TenantID    string
	SourceID    string
	ApprovedUrl string
	Approved    int64
	Enabled     int64
	IntervalUs  int64
	MaxBytes    int64
	NextAt      int64
}

func (q *Queries) ConfigurePoll(ctx context.Context, arg ConfigurePollParams) error {
	_, err := q.db.ExecContext(ctx, configurePoll,
		arg.TenantID,
		arg.SourceID,
		arg.ApprovedUrl,
		arg.Approved,
		arg.Enabled,
		arg.IntervalUs,
		arg.MaxBytes,
		arg.NextAt,
	)
	return err
}

const expirePollAttempts = `-- name: ExpirePollAttempts :exec
DELETE FROM poll_attempts WHERE state!='pending' AND charged_at<=?1
`

func (q *Queries) ExpirePollAttempts(ctx context.Context, beforeAt int64) error {
	_, err := q.db.ExecContext(ctx, expirePollAttempts, beforeAt)
	return err
}

const insertPollAttempt = `-- name: InsertPollAttempt :exec
INSERT INTO poll_attempts(id,tenant_id,source_id,started_at,lease_until,charged_at,charged_bytes,reserved_bytes,state) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,'pending')
`

type InsertPollAttemptParams struct {
	ID            string
	TenantID      string
	SourceID      string
	StartedAt     int64
	LeaseUntil    int64
	ChargedAt     int64
	ChargedBytes  int64
	ReservedBytes int64
}

func (q *Queries) InsertPollAttempt(ctx context.Context, arg InsertPollAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertPollAttempt,
		arg.ID,
		arg.TenantID,
		arg.SourceID,
		arg.StartedAt,
		arg.LeaseUntil,
		arg.ChargedAt,
		arg.ChargedBytes,
		arg.ReservedBytes,
	)
	return err
}

const markPollFailure = `-- name: MarkPollFailure :exec
UPDATE poll_sources SET claim_id=NULL,last_error=?1,last_status=?2,next_at=max(next_at,?3) WHERE tenant_id=?4 AND source_id=?5
`

type MarkPollFailureParams struct {
	LastError  string
	LastStatus int64
	HoldUntil  interface{}
	TenantID   string
	SourceID   string
}

func (q *Queries) MarkPollFailure(ctx context.Context, arg MarkPollFailureParams) error {
	_, err := q.db.ExecContext(ctx, markPollFailure,
		arg.LastError,
		arg.LastStatus,
		arg.HoldUntil,
		arg.TenantID,
		arg.SourceID,
	)
	return err
}

const markPollStarted = `-- name: MarkPollStarted :exec
UPDATE poll_sources SET claim_id=?1,last_attempt=?2,next_at=?3,last_error='pending' WHERE tenant_id=?4 AND source_id=?5
`

type MarkPollStartedParams struct {
	ClaimID     sql.NullString
	LastAttempt sql.NullInt64
	NextAt      int64
	TenantID    string
	SourceID    string
}

func (q *Queries) MarkPollStarted(ctx context.Context, arg MarkPollStartedParams) error {
	_, err := q.db.ExecContext(ctx, markPollStarted,
		arg.ClaimID,
		arg.LastAttempt,
		arg.NextAt,
		arg.TenantID,
		arg.SourceID,
	)
	return err
}

const markPollSuccess = `-- name: MarkPollSuccess :exec
UPDATE poll_sources SET claim_id=NULL,last_success=?1,last_status=?2,last_error='',etag=?3,modified=?4,next_at=max(next_at,?5) WHERE tenant_id=?6 AND source_id=?7
`

type MarkPollSuccessParams struct {
	LastSuccess sql.NullInt64
	LastStatus  int64
	Etag        string
	Modified    string
	HoldUntil   interface{}
	TenantID    string
	SourceID    string
}

func (q *Queries) MarkPollSuccess(ctx context.Context, arg MarkPollSuccessParams) error {
	_, err := q.db.ExecContext(ctx, markPollSuccess,
		arg.LastSuccess,
		arg.LastStatus,
		arg.Etag,
		arg.Modified,
		arg.HoldUntil,
		arg.TenantID,
		arg.SourceID,
	)
	return err
}

const nextPollSources = `-- name: NextPollSources :many
SELECT ps.source_id,ps.approved_url,ps.etag,ps.modified,ps.max_bytes,ps.interval_us
FROM poll_sources ps JOIN sources s ON s.tenant_id=ps.tenant_id AND s.id=ps.source_id
WHERE ps.tenant_id=?1 AND ps.enabled=1 AND ps.approved=1 AND s.enabled=1 AND s.url=ps.approved_url AND ps.next_at<=?2
ORDER BY ps.source_id LIMIT 100
`

type NextPollSourcesParams struct {
	TenantID string
	NowAt    int64
}

type NextPollSourcesRow struct {
	SourceID    string
	ApprovedUrl string
	Etag        string
	Modified    string
	MaxBytes    int64
	IntervalUs  int64
}

func (q *Queries) NextPollSources(ctx context.Context, arg NextPollSourcesParams) ([]NextPollSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, nextPollSources, arg.TenantID, arg.NowAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NextPollSourcesRow{}
	for rows.Next() {
		var i NextPollSourcesRow
		if err := rows.Scan(
			&i.SourceID,
			&i.ApprovedUrl,
			&i.Etag,
			&i.Modified,
			&i.MaxBytes,
			&i.IntervalUs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const otherPollSources = `-- name: OtherPollSources :one
SELECT count(*) FROM poll_sources WHERE NOT (tenant_id=?1 AND source_id=?2)
`

type OtherPollSourcesParams struct {
	TenantID string
	SourceID string
}

func (q *Queries) OtherPollSources(ctx context.Context, arg OtherPollSourcesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, otherPollSources, arg.TenantID, arg.SourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pendingPoll = `-- name: PendingPoll :one
SELECT a.source_id,a.reserved_bytes,a.lease_until,ps.etag,ps.modified
FROM poll_attempts a JOIN poll_sources ps ON ps.tenant_id=a.tenant_id AND ps.source_id=a.source_id AND ps.claim_id=a.id
JOIN sources s ON s.tenant_id=ps.tenant_id AND s.id=ps.source_id
WHERE a.tenant_id=?1 AND a.id=?2 AND a.state='pending' AND ps.enabled=1 AND ps.approved=1 AND s.enabled=1 AND s.url=ps.approved_url
`

type PendingPollParams struct {
	TenantID string
	ID       string
}

type PendingPollRow struct {
	SourceID      string
	ReservedBytes int64
	LeaseUntil    int64
	Etag          string
	Modified      string
}

func (q *Queries) PendingPoll(ctx context.Context, arg PendingPollParams) (PendingPollRow, error) {
	row := q.db.QueryRowContext(ctx, pendingPoll, arg.TenantID, arg.ID)
	var i PendingPollRow
	err := row.Scan(
		&i.SourceID,
		&i.ReservedBytes,
		&i.LeaseUntil,
		&i.Etag,
		&i.Modified,
	)
	return i, err
}

const pollCursor = `-- name: PollCursor :one
SELECT source_id FROM poll_cursors WHERE tenant_id=?1
`

func (q *Queries) PollCursor(ctx context.Context, tenantID string) (string, error) {
	row := q.db.QueryRowContext(ctx, pollCursor, tenantID)
	var source_id string
	err := row.Scan(&source_id)
	return source_id, err
}

const pollItemByOrigin = `-- name: PollItemByOrigin :one
SELECT id FROM articles WHERE tenant_id=?1 AND source_id=?2 AND origin_id=?3
`

type PollItemByOriginParams struct {
	TenantID string
	SourceID string
	OriginID string
}

func (q *Queries) PollItemByOrigin(ctx context.Context, arg PollItemByOriginParams) (string, error) {
	row := q.db.QueryRowContext(ctx, pollItemByOrigin, arg.TenantID, arg.SourceID, arg.OriginID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const pollItemIdentity = `-- name: PollItemIdentity :one
SELECT source_id,origin_id FROM articles WHERE tenant_id=?1 AND id=?2
`

type PollItemIdentityParams struct {
	TenantID string
	ID       string
}

type PollItemIdentityRow struct {
	SourceID string
	OriginID string
}

func (q *Queries) PollItemIdentity(ctx context.Context, arg PollItemIdentityParams) (PollItemIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, pollItemIdentity, arg.TenantID, arg.ID)
	var i PollItemIdentityRow
	err := row.Scan(&i.SourceID, &i.OriginID)
	return i, err
}

const pollSourceURL = `-- name: PollSourceURL :one
SELECT url FROM sources WHERE tenant_id=?1 AND id=?2
`

type PollSourceURLParams struct {
	TenantID string
	SourceID string
}

func (q *Queries) PollSourceURL(ctx context.Context, arg PollSourceURLParams) (string, error) {
	row := q.db.QueryRowContext(ctx, pollSourceURL, arg.TenantID, arg.SourceID)
	var url string
	err := row.Scan(&url)
	return url, err
}

const pollWindow = `-- name: PollWindow :one
SELECT count(*) AS attempts, CAST(coalesce(sum(charged_bytes),0) AS INTEGER) AS used FROM poll_attempts
`

type PollWindowRow struct {
	Attempts int64
	Used     int64
}

func (q *Queries) PollWindow(ctx context.Context) (PollWindowRow, error) {
	row := q.db.QueryRowContext(ctx, pollWindow)
	var i PollWindowRow
	err := row.Scan(&i.Attempts, &i.Used)
	return i, err
}

const putPollItem = `-- name: PutPollItem :execrows
INSERT INTO articles(tenant_id,id,source_id,origin_id,url,title,body,content_hash,published_at,observed_at)
VALUES(?1,?2,?3,?4,?5,?6,'',?7,?8,?9) ON CONFLICT(tenant_id,id) DO UPDATE SET url=excluded.url,title=excluded.title,body='',content_hash=excluded.content_hash,published_at=excluded.published_at,observed_at=excluded.observed_at
WHERE articles.content_hash!=excluded.content_hash OR articles.url!=excluded.url OR articles.published_at IS NOT excluded.published_at OR articles.body!=''
`

type PutPollItemParams struct {
	TenantID    string
	ID          string
	SourceID    string
	OriginID    string
	Url         string
	Title       string
	ContentHash string
	PublishedAt sql.NullInt64
	ObservedAt  int64
}

func (q *Queries) PutPollItem(ctx context.Context, arg PutPollItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, putPollItem,
		arg.TenantID,
		arg.ID,
		arg.SourceID,
		arg.OriginID,
		arg.Url,
		arg.Title,
		arg.ContentHash,
		arg.PublishedAt,
		arg.ObservedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetPollSchedule = `-- name: ResetPollSchedule :execrows
UPDATE poll_sources SET next_at=max(CAST(?1 AS INTEGER),coalesce(last_attempt+interval_us,0)),
last_error=CASE WHEN claim_id IS NOT NULL THEN 'reset' ELSE last_error END,claim_id=NULL
WHERE tenant_id=?2 AND source_id=?3
`

type ResetPollScheduleParams struct {
	NextAt   int64
	TenantID string
	SourceID string
}

func (q *Queries) ResetPollSchedule(ctx context.Context, arg ResetPollScheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetPollSchedule, arg.NextAt, arg.TenantID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const settlePollAttempt = `-- name: SettlePollAttempt :exec
UPDATE poll_attempts SET state='done',charged_bytes=?1,charged_at=?2 WHERE tenant_id=?3 AND id=?4
`

type SettlePollAttemptParams struct {
	ChargedBytes int64
	ChargedAt    int64
	TenantID     string
	ID           string
}

func (q *Queries) SettlePollAttempt(ctx context.Context, arg SettlePollAttemptParams) error {
	_, err := q.db.ExecContext(ctx, settlePollAttempt,
		arg.ChargedBytes,
		arg.ChargedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const sourceItemCount = `-- name: SourceItemCount :one
SELECT count(*) FROM articles WHERE tenant_id=?1 AND source_id=?2
`

type SourceItemCountParams struct {
	TenantID string
	SourceID string
}

func (q *Queries) SourceItemCount(ctx context.Context, arg SourceItemCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sourceItemCount, arg.TenantID, arg.SourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sourceVersionCount = `-- name: SourceVersionCount :one
SELECT count(*) FROM article_versions v JOIN articles a ON a.tenant_id=v.tenant_id AND a.id=v.article_id WHERE a.tenant_id=?1 AND a.source_id=?2
`

type SourceVersionCountParams struct {
	TenantID string
	SourceID string
}

func (q *Queries) SourceVersionCount(ctx context.Context, arg SourceVersionCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sourceVersionCount, arg.TenantID, arg.SourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
