// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package sqlc

import (
	"context"
)

const deleteExpiredArticles = `-- name: DeleteExpiredArticles :execrows
DELETE FROM articles WHERE rowid IN (
  SELECT rowid FROM articles
  WHERE articles.tenant_id=?1
    AND articles.observed_at<?2
  ORDER BY observed_at,rowid LIMIT 1000
)
`

type DeleteExpiredArticlesParams struct {
	TargetTenant string
	BeforeAt     int64
}

func (q *Queries) DeleteExpiredArticles(ctx context.Context, arg DeleteExpiredArticlesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredArticles, arg.TargetTenant, arg.BeforeAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredPollAttempts = `-- name: DeleteExpiredPollAttempts :execrows
DELETE FROM poll_attempts WHERE rowid IN (
  SELECT rowid FROM poll_attempts
  WHERE poll_attempts.tenant_id=?1
    AND poll_attempts.state!='pending'
    AND poll_attempts.charged_at<=?2
  ORDER BY charged_at,rowid LIMIT 1000
)
`

type DeleteExpiredPollAttemptsParams struct {
	TargetTenant string
	BeforeAt     int64
}

func (q *Queries) DeleteExpiredPollAttempts(ctx context.Context, arg DeleteExpiredPollAttemptsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredPollAttempts, arg.TargetTenant, arg.BeforeAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredQuerySnapshots = `-- name: DeleteExpiredQuerySnapshots :execrows
DELETE FROM query_snapshots WHERE rowid IN (
  SELECT query_snapshots.rowid FROM query_snapshots
  WHERE query_snapshots.tenant_id=?1
    AND query_snapshots.retain_until<=?2
    AND NOT EXISTS (
      SELECT 1 FROM query_work
      WHERE query_work.tenant_id=query_snapshots.tenant_id
        AND query_work.snapshot_id=query_snapshots.id
    )
	AND NOT EXISTS (
	  SELECT 1 FROM feedback_events saved
	  WHERE saved.tenant_id=query_snapshots.tenant_id
	    AND saved.snapshot_id=query_snapshots.id
	    AND saved.action='save'
	    AND NOT EXISTS (
	      SELECT 1 FROM feedback_events reversal
	      WHERE reversal.tenant_id=saved.tenant_id
	        AND reversal.reverses_event_id=saved.id
	    )
	)
  ORDER BY retain_until,query_snapshots.rowid LIMIT 1000
)
`

type DeleteExpiredQuerySnapshotsParams struct {
	TargetTenant string
	BeforeAt     int64
}

func (q *Queries) DeleteExpiredQuerySnapshots(ctx context.Context, arg DeleteExpiredQuerySnapshotsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredQuerySnapshots, arg.TargetTenant, arg.BeforeAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredQueryWork = `-- name: DeleteExpiredQueryWork :execrows
DELETE FROM query_work WHERE rowid IN (
  SELECT rowid FROM query_work
  WHERE query_work.tenant_id=?1
    AND query_work.retain_until<=?2
    AND work_state IN ('done','failed')
    AND spend_state='settled'
  ORDER BY retain_until,rowid LIMIT 1000
)
`

type DeleteExpiredQueryWorkParams struct {
	TargetTenant string
	BeforeAt     int64
}

func (q *Queries) DeleteExpiredQueryWork(ctx context.Context, arg DeleteExpiredQueryWorkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredQueryWork, arg.TargetTenant, arg.BeforeAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSupersededArticleVersions = `-- name: DeleteSupersededArticleVersions :execrows
DELETE FROM article_versions WHERE rowid IN (
  SELECT article_versions.rowid FROM article_versions
  WHERE article_versions.tenant_id=?1
    AND article_versions.observed_at<?2
    AND NOT EXISTS (
      SELECT 1 FROM articles
      WHERE articles.tenant_id=article_versions.tenant_id
        AND articles.id=article_versions.article_id
        AND articles.content_hash=article_versions.content_hash
    )
  ORDER BY observed_at,article_versions.rowid LIMIT 1000
)
`

type DeleteSupersededArticleVersionsParams struct {
	TargetTenant string
	BeforeAt     int64
}

func (q *Queries) DeleteSupersededArticleVersions(ctx context.Context, arg DeleteSupersededArticleVersionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSupersededArticleVersions, arg.TargetTenant, arg.BeforeAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unhealthyPollSources = `-- name: UnhealthyPollSources :one
SELECT count(*) FROM poll_sources ps
LEFT JOIN poll_attempts pa ON pa.id=ps.claim_id AND pa.tenant_id=ps.tenant_id
WHERE ps.tenant_id=?1
  AND ps.approved=1
  AND ps.enabled=1
  AND (
    ps.last_success IS NULL
    OR ps.last_success>CAST(?2 AS INTEGER)
    OR ps.last_success<CAST(?2 AS INTEGER)-(2*ps.interval_us)
    OR (ps.last_error!='' AND ps.last_error!='pending')
    OR (ps.claim_id IS NOT NULL AND (pa.id IS NULL OR pa.state!='pending' OR pa.lease_until<=CAST(?2 AS INTEGER)))
  )
`

type UnhealthyPollSourcesParams struct {
	TargetTenant string
	NowAt        int64
}

func (q *Queries) UnhealthyPollSources(ctx context.Context, arg UnhealthyPollSourcesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, unhealthyPollSources, arg.TargetTenant, arg.NowAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const unreconciledQueryWork = `-- name: UnreconciledQueryWork :one
SELECT count(*) FROM query_work
WHERE query_work.tenant_id=?1 AND query_work.spend_state='uncertain'
`

func (q *Queries) UnreconciledQueryWork(ctx context.Context, targetTenant string) (int64, error) {
	row := q.db.QueryRowContext(ctx, unreconciledQueryWork, targetTenant)
	var count int64
	err := row.Scan(&count)
	return count, err
}
