// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Article struct {
	Rowid       int64
	TenantID    string
	ID          string
	SourceID    string
	OriginID    string
	Url         string
	Title       string
	Body        string
	ContentHash string
	PublishedAt sql.NullInt64
	ObservedAt  int64
}

type ArticleVersion struct {
	TenantID    string
	ArticleID   string
	ContentHash string
	Title       string
	Body        string
	ObservedAt  int64
}

type Feed struct {
	TenantID string
	ID       string
	Title    string
}

type FeedSource struct {
	TenantID string
	FeedID   string
	SourceID string
}

type Source struct {
	TenantID string
	ID       string
	Url      string
	Title    string
}

type Tenant struct {
	ID        string
	CreatedAt int64
}
