// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type ApiKey struct {
	ID         string
	TenantID   string
	Digest     []byte
	Scopes     int64
	CreatedAt  int64
	LastUsedAt sql.NullInt64
	RevokedAt  sql.NullInt64
}

type Article struct {
	Rowid       int64
	TenantID    string
	ID          string
	SourceID    string
	OriginID    string
	Url         string
	Title       string
	Body        string
	ContentHash string
	PublishedAt sql.NullInt64
	ObservedAt  int64
}

type ArticleVersion struct {
	TenantID    string
	ArticleID   string
	ContentHash string
	Title       string
	Body        string
	ObservedAt  int64
}

type Budget struct {
	TenantID    string
	LimitMicros int64
	SpentMicros int64
	HeldMicros  int64
}

type Feed struct {
	TenantID    string
	ID          string
	Title       string
	Revision    int64
	Enabled     int64
	Preferences string
}

type FeedSource struct {
	TenantID string
	FeedID   string
	SourceID string
}

type PollAttempt struct {
	ID            string
	TenantID      string
	SourceID      string
	StartedAt     int64
	LeaseUntil    int64
	ChargedAt     int64
	ChargedBytes  int64
	ReservedBytes int64
	State         string
}

type PollCursor struct {
	TenantID string
	SourceID string
}

type PollSource struct {
	TenantID    string
	SourceID    string
	ApprovedUrl string
	Approved    int64
	Enabled     int64
	IntervalUs  int64
	MaxBytes    int64
	NextAt      int64
	Etag        string
	Modified    string
	LastSuccess sql.NullInt64
	LastAttempt sql.NullInt64
	LastStatus  int64
	LastError   string
	ClaimID     sql.NullString
}

type QuerySnapshot struct {
	TenantID            string
	ID                  string
	FeedID              string
	RequestHash         []byte
	FeedRevision        int64
	CorpusRevision      int64
	EntitlementRevision int64
	RankerVersion       string
	Mode                string
	GeneratedAt         int64
	ExpiresAt           int64
	RetainUntil         int64
	Items               string
	Details             string
}

type QueryWork struct {
	TenantID            string
	ID                  string
	KeyHash             []byte
	RequestHash         []byte
	FeedID              string
	FeedRevision        int64
	CorpusRevision      int64
	EntitlementRevision int64
	RankerVersion       string
	ItemLimit           int64
	SinceAt             int64
	CreatedAt           int64
	LeaseUntil          int64
	RetainUntil         int64
	CacheTtl            int64
	WorkState           string
	SpendState          string
	ReservedMicros      int64
	ActualMicros        sql.NullInt64
	SnapshotID          sql.NullString
}

type Source struct {
	TenantID string
	ID       string
	Url      string
	Title    string
	Enabled  int64
}

type Tenant struct {
	ID                  string
	CreatedAt           int64
	CorpusRevision      int64
	EntitlementRevision int64
}
