// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createQuerySnapshot = `-- name: CreateQuerySnapshot :exec
INSERT INTO query_snapshots(tenant_id,id,feed_id,request_hash,feed_revision,corpus_revision,entitlement_revision,ranker_version,mode,generated_at,expires_at,retain_until,items)
VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type CreateQuerySnapshotParams struct {
	TenantID            string
	ID                  string
	FeedID              string
	RequestHash         []byte
	FeedRevision        int64
	CorpusRevision      int64
	EntitlementRevision int64
	RankerVersion       string
	Mode                string
	GeneratedAt         int64
	ExpiresAt           int64
	RetainUntil         int64
	Items               string
}

func (q *Queries) CreateQuerySnapshot(ctx context.Context, arg CreateQuerySnapshotParams) error {
	_, err := q.db.ExecContext(ctx, createQuerySnapshot,
		arg.TenantID,
		arg.ID,
		arg.FeedID,
		arg.RequestHash,
		arg.FeedRevision,
		arg.CorpusRevision,
		arg.EntitlementRevision,
		arg.RankerVersion,
		arg.Mode,
		arg.GeneratedAt,
		arg.ExpiresAt,
		arg.RetainUntil,
		arg.Items,
	)
	return err
}

const createQueryWork = `-- name: CreateQueryWork :exec
INSERT INTO query_work(tenant_id,id,key_hash,request_hash,feed_id,feed_revision,corpus_revision,entitlement_revision,ranker_version,item_limit,since_at,created_at,lease_until,retain_until,cache_ttl,work_state,spend_state,reserved_micros,actual_micros,snapshot_id)
VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type CreateQueryWorkParams struct {
	TenantID            string
	ID                  string
	KeyHash             []byte
	RequestHash         []byte
	FeedID              string
	FeedRevision        int64
	CorpusRevision      int64
	EntitlementRevision int64
	RankerVersion       string
	ItemLimit           int64
	SinceAt             int64
	CreatedAt           int64
	LeaseUntil          int64
	RetainUntil         int64
	CacheTtl            int64
	WorkState           string
	SpendState          string
	ReservedMicros      int64
	ActualMicros        sql.NullInt64
	SnapshotID          sql.NullString
}

func (q *Queries) CreateQueryWork(ctx context.Context, arg CreateQueryWorkParams) error {
	_, err := q.db.ExecContext(ctx, createQueryWork,
		arg.TenantID,
		arg.ID,
		arg.KeyHash,
		arg.RequestHash,
		arg.FeedID,
		arg.FeedRevision,
		arg.CorpusRevision,
		arg.EntitlementRevision,
		arg.RankerVersion,
		arg.ItemLimit,
		arg.SinceAt,
		arg.CreatedAt,
		arg.LeaseUntil,
		arg.RetainUntil,
		arg.CacheTtl,
		arg.WorkState,
		arg.SpendState,
		arg.ReservedMicros,
		arg.ActualMicros,
		arg.SnapshotID,
	)
	return err
}

const detachSource = `-- name: DetachSource :execrows
DELETE FROM feed_sources WHERE tenant_id=? AND feed_id=? AND source_id=?
`

type DetachSourceParams struct {
	TenantID string
	FeedID   string
	SourceID string
}

func (q *Queries) DetachSource(ctx context.Context, arg DetachSourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, detachSource, arg.TenantID, arg.FeedID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expiredQueryWork = `-- name: ExpiredQueryWork :many
SELECT tenant_id, id, key_hash, request_hash, feed_id, feed_revision, corpus_revision, entitlement_revision, ranker_version, item_limit, since_at, created_at, lease_until, retain_until, cache_ttl, work_state, spend_state, reserved_micros, actual_micros, snapshot_id FROM query_work WHERE tenant_id=? AND work_state='pending' AND lease_until<=? ORDER BY lease_until,id LIMIT 100
`

type ExpiredQueryWorkParams struct {
	TenantID   string
	LeaseUntil int64
}

func (q *Queries) ExpiredQueryWork(ctx context.Context, arg ExpiredQueryWorkParams) ([]QueryWork, error) {
	rows, err := q.db.QueryContext(ctx, expiredQueryWork, arg.TenantID, arg.LeaseUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryWork{}
	for rows.Next() {
		var i QueryWork
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.KeyHash,
			&i.RequestHash,
			&i.FeedID,
			&i.FeedRevision,
			&i.CorpusRevision,
			&i.EntitlementRevision,
			&i.RankerVersion,
			&i.ItemLimit,
			&i.SinceAt,
			&i.CreatedAt,
			&i.LeaseUntil,
			&i.RetainUntil,
			&i.CacheTtl,
			&i.WorkState,
			&i.SpendState,
			&i.ReservedMicros,
			&i.ActualMicros,
			&i.SnapshotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findQueryCache = `-- name: FindQueryCache :one
SELECT tenant_id, id, feed_id, request_hash, feed_revision, corpus_revision, entitlement_revision, ranker_version, mode, generated_at, expires_at, retain_until, items, details FROM query_snapshots WHERE tenant_id=? AND feed_id=? AND request_hash=? AND feed_revision=? AND corpus_revision=? AND entitlement_revision=? AND ranker_version=? AND expires_at>? ORDER BY generated_at DESC,id LIMIT 1
`

type FindQueryCacheParams struct {
	TenantID            string
	FeedID              string
	RequestHash         []byte
	FeedRevision        int64
	CorpusRevision      int64
	EntitlementRevision int64
	RankerVersion       string
	ExpiresAt           int64
}

func (q *Queries) FindQueryCache(ctx context.Context, arg FindQueryCacheParams) (QuerySnapshot, error) {
	row := q.db.QueryRowContext(ctx, findQueryCache,
		arg.TenantID,
		arg.FeedID,
		arg.RequestHash,
		arg.FeedRevision,
		arg.CorpusRevision,
		arg.EntitlementRevision,
		arg.RankerVersion,
		arg.ExpiresAt,
	)
	var i QuerySnapshot
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.FeedID,
		&i.RequestHash,
		&i.FeedRevision,
		&i.CorpusRevision,
		&i.EntitlementRevision,
		&i.RankerVersion,
		&i.Mode,
		&i.GeneratedAt,
		&i.ExpiresAt,
		&i.RetainUntil,
		&i.Items,
		&i.Details,
	)
	return i, err
}

const getBudget = `-- name: GetBudget :one
SELECT tenant_id, limit_micros, spent_micros, held_micros FROM budgets WHERE tenant_id=?
`

func (q *Queries) GetBudget(ctx context.Context, tenantID string) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudget, tenantID)
	var i Budget
	err := row.Scan(
		&i.TenantID,
		&i.LimitMicros,
		&i.SpentMicros,
		&i.HeldMicros,
	)
	return i, err
}

const getQuerySnapshot = `-- name: GetQuerySnapshot :one
SELECT tenant_id, id, feed_id, request_hash, feed_revision, corpus_revision, entitlement_revision, ranker_version, mode, generated_at, expires_at, retain_until, items, details FROM query_snapshots WHERE tenant_id=? AND id=? AND retain_until>?
`

type GetQuerySnapshotParams struct {
	TenantID    string
	ID          string
	RetainUntil int64
}

func (q *Queries) GetQuerySnapshot(ctx context.Context, arg GetQuerySnapshotParams) (QuerySnapshot, error) {
	row := q.db.QueryRowContext(ctx, getQuerySnapshot, arg.TenantID, arg.ID, arg.RetainUntil)
	var i QuerySnapshot
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.FeedID,
		&i.RequestHash,
		&i.FeedRevision,
		&i.CorpusRevision,
		&i.EntitlementRevision,
		&i.RankerVersion,
		&i.Mode,
		&i.GeneratedAt,
		&i.ExpiresAt,
		&i.RetainUntil,
		&i.Items,
		&i.Details,
	)
	return i, err
}

const queryArticle = `-- name: QueryArticle :one
SELECT a.id,a.source_id,a.content_hash,a.title,a.url,a.observed_at,a.published_at,s.title AS source_name FROM articles a
JOIN feed_sources f ON f.tenant_id=a.tenant_id AND f.source_id=a.source_id
JOIN sources s ON s.tenant_id=a.tenant_id AND s.id=a.source_id
WHERE a.tenant_id=? AND f.feed_id=? AND a.id=? AND s.enabled=1
`

type QueryArticleParams struct {
	TenantID string
	FeedID   string
	ID       string
}

type QueryArticleRow struct {
	ID          string
	SourceID    string
	ContentHash string
	Title       string
	Url         string
	ObservedAt  int64
	PublishedAt sql.NullInt64
	SourceName  string
}

func (q *Queries) QueryArticle(ctx context.Context, arg QueryArticleParams) (QueryArticleRow, error) {
	row := q.db.QueryRowContext(ctx, queryArticle, arg.TenantID, arg.FeedID, arg.ID)
	var i QueryArticleRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ContentHash,
		&i.Title,
		&i.Url,
		&i.ObservedAt,
		&i.PublishedAt,
		&i.SourceName,
	)
	return i, err
}

const queryScope = `-- name: QueryScope :one
SELECT f.revision,t.corpus_revision,t.entitlement_revision FROM feeds f
JOIN tenants t ON t.id=f.tenant_id WHERE f.tenant_id=? AND f.id=? AND f.enabled=1
`

type QueryScopeParams struct {
	TenantID string
	ID       string
}

type QueryScopeRow struct {
	Revision            int64
	CorpusRevision      int64
	EntitlementRevision int64
}

func (q *Queries) QueryScope(ctx context.Context, arg QueryScopeParams) (QueryScopeRow, error) {
	row := q.db.QueryRowContext(ctx, queryScope, arg.TenantID, arg.ID)
	var i QueryScopeRow
	err := row.Scan(&i.Revision, &i.CorpusRevision, &i.EntitlementRevision)
	return i, err
}

const querySourceAllowed = `-- name: QuerySourceAllowed :one
SELECT count(*) FROM feed_sources f JOIN sources s ON s.tenant_id=f.tenant_id AND s.id=f.source_id
WHERE f.tenant_id=? AND f.feed_id=? AND f.source_id=? AND s.enabled=1
`

type QuerySourceAllowedParams struct {
	TenantID string
	FeedID   string
	SourceID string
}

func (q *Queries) QuerySourceAllowed(ctx context.Context, arg QuerySourceAllowedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, querySourceAllowed, arg.TenantID, arg.FeedID, arg.SourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const queryWorkByID = `-- name: QueryWorkByID :one
SELECT tenant_id, id, key_hash, request_hash, feed_id, feed_revision, corpus_revision, entitlement_revision, ranker_version, item_limit, since_at, created_at, lease_until, retain_until, cache_ttl, work_state, spend_state, reserved_micros, actual_micros, snapshot_id FROM query_work WHERE tenant_id=? AND id=?
`

type QueryWorkByIDParams struct {
	TenantID string
	ID       string
}

func (q *Queries) QueryWorkByID(ctx context.Context, arg QueryWorkByIDParams) (QueryWork, error) {
	row := q.db.QueryRowContext(ctx, queryWorkByID, arg.TenantID, arg.ID)
	var i QueryWork
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.KeyHash,
		&i.RequestHash,
		&i.FeedID,
		&i.FeedRevision,
		&i.CorpusRevision,
		&i.EntitlementRevision,
		&i.RankerVersion,
		&i.ItemLimit,
		&i.SinceAt,
		&i.CreatedAt,
		&i.LeaseUntil,
		&i.RetainUntil,
		&i.CacheTtl,
		&i.WorkState,
		&i.SpendState,
		&i.ReservedMicros,
		&i.ActualMicros,
		&i.SnapshotID,
	)
	return i, err
}

const queryWorkByKey = `-- name: QueryWorkByKey :one
SELECT tenant_id, id, key_hash, request_hash, feed_id, feed_revision, corpus_revision, entitlement_revision, ranker_version, item_limit, since_at, created_at, lease_until, retain_until, cache_ttl, work_state, spend_state, reserved_micros, actual_micros, snapshot_id FROM query_work WHERE tenant_id=? AND key_hash=?
`

type QueryWorkByKeyParams struct {
	TenantID string
	KeyHash  []byte
}

func (q *Queries) QueryWorkByKey(ctx context.Context, arg QueryWorkByKeyParams) (QueryWork, error) {
	row := q.db.QueryRowContext(ctx, queryWorkByKey, arg.TenantID, arg.KeyHash)
	var i QueryWork
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.KeyHash,
		&i.RequestHash,
		&i.FeedID,
		&i.FeedRevision,
		&i.CorpusRevision,
		&i.EntitlementRevision,
		&i.RankerVersion,
		&i.ItemLimit,
		&i.SinceAt,
		&i.CreatedAt,
		&i.LeaseUntil,
		&i.RetainUntil,
		&i.CacheTtl,
		&i.WorkState,
		&i.SpendState,
		&i.ReservedMicros,
		&i.ActualMicros,
		&i.SnapshotID,
	)
	return i, err
}

const reserveBudget = `-- name: ReserveBudget :execrows
UPDATE budgets SET held_micros=held_micros+?1 WHERE tenant_id=?2 AND ?1<=limit_micros-spent_micros-held_micros
`

type ReserveBudgetParams struct {
	Amount   int64
	TenantID string
}

func (q *Queries) ReserveBudget(ctx context.Context, arg ReserveBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reserveBudget, arg.Amount, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retainQuerySnapshot = `-- name: RetainQuerySnapshot :exec
UPDATE query_snapshots SET retain_until=max(retain_until,?1) WHERE tenant_id=?2 AND id=?3
`

type RetainQuerySnapshotParams struct {
	RetainUntil interface{}
	TenantID    string
	ID          string
}

func (q *Queries) RetainQuerySnapshot(ctx context.Context, arg RetainQuerySnapshotParams) error {
	_, err := q.db.ExecContext(ctx, retainQuerySnapshot, arg.RetainUntil, arg.TenantID, arg.ID)
	return err
}

const setBudget = `-- name: SetBudget :execrows
INSERT INTO budgets(tenant_id,limit_micros) VALUES(?,?) ON CONFLICT(tenant_id) DO UPDATE SET limit_micros=excluded.limit_micros
WHERE budgets.spent_micros<=excluded.limit_micros AND budgets.held_micros<=excluded.limit_micros-budgets.spent_micros
`

type SetBudgetParams struct {
	TenantID    string
	LimitMicros int64
}

func (q *Queries) SetBudget(ctx context.Context, arg SetBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setBudget, arg.TenantID, arg.LimitMicros)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setFeedEnabled = `-- name: SetFeedEnabled :execrows
UPDATE feeds SET enabled=? WHERE tenant_id=? AND id=?
`

type SetFeedEnabledParams struct {
	Enabled  int64
	TenantID string
	ID       string
}

func (q *Queries) SetFeedEnabled(ctx context.Context, arg SetFeedEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setFeedEnabled, arg.Enabled, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSourceEnabled = `-- name: SetSourceEnabled :execrows
UPDATE sources SET enabled=? WHERE tenant_id=? AND id=?
`

type SetSourceEnabledParams struct {
	Enabled  int64
	TenantID string
	ID       string
}

func (q *Queries) SetSourceEnabled(ctx context.Context, arg SetSourceEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSourceEnabled, arg.Enabled, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const settleBudget = `-- name: SettleBudget :execrows
UPDATE budgets SET held_micros=held_micros-?1,spent_micros=spent_micros+?2 WHERE tenant_id=?3 AND held_micros>=?1
`

type SettleBudgetParams struct {
	Reserved int64
	Actual   int64
	TenantID string
}

func (q *Queries) SettleBudget(ctx context.Context, arg SettleBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, settleBudget, arg.Reserved, arg.Actual, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateQueryWork = `-- name: UpdateQueryWork :exec
UPDATE query_work SET work_state=?,spend_state=?,actual_micros=?,snapshot_id=? WHERE tenant_id=? AND id=?
`

type UpdateQueryWorkParams struct {
	WorkState    string
	SpendState   string
	ActualMicros sql.NullInt64
	SnapshotID   sql.NullString
	TenantID     string
	ID           string
}

func (q *Queries) UpdateQueryWork(ctx context.Context, arg UpdateQueryWorkParams) error {
	_, err := q.db.ExecContext(ctx, updateQueryWork,
		arg.WorkState,
		arg.SpendState,
		arg.ActualMicros,
		arg.SnapshotID,
		arg.TenantID,
		arg.ID,
	)
	return err
}
