// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retrieval.sql

package sqlc

import (
	"context"
	"database/sql"
)

const configureFeedPreferences = `-- name: ConfigureFeedPreferences :execrows
UPDATE feeds SET preferences=? WHERE tenant_id=? AND id=? AND enabled=1
`

type ConfigureFeedPreferencesParams struct {
	Preferences string
	TenantID    string
	ID          string
}

func (q *Queries) ConfigureFeedPreferences(ctx context.Context, arg ConfigureFeedPreferencesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, configureFeedPreferences, arg.Preferences, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const feedPreferences = `-- name: FeedPreferences :one
SELECT preferences FROM feeds WHERE tenant_id=? AND id=? AND enabled=1
`

type FeedPreferencesParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FeedPreferences(ctx context.Context, arg FeedPreferencesParams) (string, error) {
	row := q.db.QueryRowContext(ctx, feedPreferences, arg.TenantID, arg.ID)
	var preferences string
	err := row.Scan(&preferences)
	return preferences, err
}

const retrievalSourceAllowed = `-- name: RetrievalSourceAllowed :one
SELECT count(*) FROM feeds fd JOIN json_each(fd.preferences,'$.sources') r
JOIN feed_sources fs ON fs.tenant_id=fd.tenant_id AND fs.feed_id=fd.id AND fs.source_id=json_extract(r.value,'$.source_id')
JOIN sources s ON s.tenant_id=fs.tenant_id AND s.id=fs.source_id
WHERE fd.tenant_id=? AND fd.id=? AND fs.source_id=? AND fd.enabled=1 AND s.enabled=1
`

type RetrievalSourceAllowedParams struct {
	TenantID string
	ID       string
	SourceID string
}

func (q *Queries) RetrievalSourceAllowed(ctx context.Context, arg RetrievalSourceAllowedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, retrievalSourceAllowed, arg.TenantID, arg.ID, arg.SourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const retrievalSources = `-- name: RetrievalSources :many
SELECT CAST(json_extract(r.value,'$.source_id') AS TEXT) AS source_id,
CAST(coalesce(s.title,'') AS TEXT) AS title,
CAST(CASE WHEN fs.source_id IS NOT NULL AND s.enabled=1 THEN 1 ELSE 0 END AS INTEGER) AS allowed,
p.last_success,CAST(coalesce(p.interval_us,0) AS INTEGER) AS interval_us
FROM feeds fd JOIN json_each(fd.preferences,'$.sources') r
LEFT JOIN feed_sources fs ON fs.tenant_id=fd.tenant_id AND fs.feed_id=fd.id AND fs.source_id=json_extract(r.value,'$.source_id')
LEFT JOIN sources s ON s.tenant_id=fs.tenant_id AND s.id=fs.source_id
LEFT JOIN poll_sources p ON p.tenant_id=s.tenant_id AND p.source_id=s.id
WHERE fd.tenant_id=? AND fd.id=? AND fd.enabled=1 ORDER BY source_id LIMIT 101
`

type RetrievalSourcesParams struct {
	TenantID string
	ID       string
}

type RetrievalSourcesRow struct {
	SourceID    string
	Title       string
	Allowed     int64
	LastSuccess sql.NullInt64
	IntervalUs  int64
}

func (q *Queries) RetrievalSources(ctx context.Context, arg RetrievalSourcesParams) ([]RetrievalSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, retrievalSources, arg.TenantID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetrievalSourcesRow{}
	for rows.Next() {
		var i RetrievalSourcesRow
		if err := rows.Scan(
			&i.SourceID,
			&i.Title,
			&i.Allowed,
			&i.LastSuccess,
			&i.IntervalUs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotDetails = `-- name: SnapshotDetails :exec
UPDATE query_snapshots SET details=? WHERE tenant_id=? AND id=?
`

type SnapshotDetailsParams struct {
	Details  string
	TenantID string
	ID       string
}

func (q *Queries) SnapshotDetails(ctx context.Context, arg SnapshotDetailsParams) error {
	_, err := q.db.ExecContext(ctx, snapshotDetails, arg.Details, arg.TenantID, arg.ID)
	return err
}
