[www]
listen = 127.0.0.1:9000
pm = static
pm.max_children = 2
pm.max_requests = 250
request_terminate_timeout = 25s
request_terminate_timeout_track_finished = yes
clear_env = no
php_admin_value[memory_limit] = 96M
php_admin_value[session.save_path] = /app/storage
php_admin_flag[session.cookie_secure] = on
php_admin_flag[session.cookie_httponly] = on
php_admin_value[session.cookie_samesite] = Lax
