"""Collect notices for linked application modules, not the entire tool graph."""
import pathlib
import subprocess
import sys
from check_boundaries import decode_stream

packages = decode_stream(subprocess.check_output(["go", "list", "-deps", "-json", "./cmd/northway"], text=True))
modules = {}
for package in packages:
    module = package.get("Module")
    if module and not module.get("Main"):
        modules[module["Path"]] = module
parts = ["Third-party application module notices\n\nGenerated by scripts/collect_licenses.py. Go's license is distributed separately.\n"]
for name, module in sorted(modules.items()):
    directory = pathlib.Path(module["Dir"])
    notices = sorted(p for p in directory.iterdir() if p.is_file() and p.name.upper().startswith(("LICENSE", "COPYING", "NOTICE")))
    if not notices:
        raise SystemExit("No license notice found for " + name)
    parts.append(f"\n{'=' * 72}\n{name} {module['Version']}\n")
    for notice in notices:
        parts.append("\n" + notice.name + "\n" + notice.read_text(encoding="utf-8").replace("\r\n", "\n") + "\n")
text = "".join(parts).rstrip() + "\n"
target = pathlib.Path("THIRD_PARTY_NOTICES.txt")
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != text:
        raise SystemExit("third-party notices drift; run make licenses")
    print(f"PASS: notices for {len(modules)} linked third-party modules")
else:
    target.write_text(text)
    print(f"Collected notices for {len(modules)} linked third-party modules")
