-- +goose Up
ALTER TABLE poll_sources ADD COLUMN mode TEXT NOT NULL DEFAULT 'feed' CHECK(mode IN ('feed','html'));
ALTER TABLE poll_sources ADD COLUMN preview_allowed BIGINT NOT NULL DEFAULT 0 CHECK(preview_allowed IN (0,1));
ALTER TABLE poll_sources ADD COLUMN robots_until BIGINT NOT NULL DEFAULT 0;
CREATE TABLE collection_items(
 tenant_id TEXT NOT NULL,source_id TEXT NOT NULL,id TEXT NOT NULL,revision BIGINT NOT NULL,
 fingerprint TEXT NOT NULL,payload TEXT NOT NULL CHECK(octet_length(payload)<=16384),
 PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,source_id) REFERENCES sources(tenant_id,id)
);
CREATE TABLE collection_events(
 sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id TEXT NOT NULL,source_id TEXT NOT NULL,
 item_id TEXT NOT NULL,revision BIGINT NOT NULL,payload TEXT NOT NULL CHECK(octet_length(payload)<=16384),
 UNIQUE(tenant_id,item_id,revision),FOREIGN KEY(tenant_id,source_id) REFERENCES sources(tenant_id,id)
);
CREATE INDEX collection_event_tenant_cursor ON collection_events(tenant_id,sequence);
CREATE TABLE collection_hosts(host TEXT PRIMARY KEY,next_at BIGINT NOT NULL);

CREATE UNIQUE INDEX collection_seed_url ON poll_sources(tenant_id,approved_url) WHERE mode='html';
